### ISSUE TITLE
단어장

### ISSUE THREAD

**Issue by HomelessRaven** [FriedrichvonEbert/TheNewOrderKoreanTranslation#2]
Himmler: 힘러
Triumvirate: 트리움비라투스
Ostland: 오스틀란트
Luftwaffe: 루프트바페
Moskovien: 모스코비엔
Ordensstaat: 기사단국
Globalpläne: 세계계획
Das Großgermanische Reich der Deutschen Nation: 독일 민족의 대게르만국
The German Civil War: 독일 내전
Reich: 라이히
The New Order : 신세계 질서
The South African War: 남아프리카 전쟁

**Comment by HomelessRaven** [comment]
Kempeitail: 헌병대, 일본 헌병대 등

**Comment by HomelessRaven** [comment]
Free Aviators: 자유 비행단
Nowa Polska: 노바 폴스카

**Comment by BOBK235** [comment]
Oil Crisis: 석유 파동

**Comment by gyulsa** [comment]
Her Majesty's Most Loyal Resistance: 여왕 폐하의 충성스러운 저항군
HMMLR: 저항군(임시)

**Comment by FriedrichvonEbert** [comment]
Unity-Pakt, Einheitspakt: 아인하이츠팍트
