### ISSUE TITLE
슈페어 용어 정리(추가중)

### ISSUE THREAD

**Issue by LaFayette319** [FriedrichvonEbert/TheNewOrderKoreanTranslation#517]
Reichstag -> 라이히스탁
Tresckow -> 트레슈코프
Kiesinger -> 키징어
Zollverein -> 졸페어라인(논의중)
Unity-Pakt, Einheitspakt -> 아인하이츠팍트

**Comment by LaFayette319** [comment]
RND(Reichsnachrictendienst): 국가정보국

**Comment by LaFayette319** [comment]
Volkshalle -> 민족대회당
Oberländer ->오버랜더 (이 외에도 ä는 ㅐ로 하는 것을 권장)

**Comment by allex101** [comment]
Baltischer Bund -> 발트 동맹

**Comment by allex101** [comment]
Baltischer Bund ->발트 연방
